export type IconsType =
  | "loading"
  | "add"
  | "close"
  | "alertInfo"
  | "alertWarning"
  | "alertSuccess"
  | "alertError"
  | "camera"
  | "user"
  | "trash"
  | "cart"
  | "arrowDoubleRight"
  | "noImg"
  | "star";
